watch_stylesheet: true
watch_config: true
debug: false

komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"

bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "bottom"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: true
      round_corners: false
      border_color: "None"
    window_flags:
      always_on_top: true
      windows_app_bar: true
      hide_on_fullscreen: true
    dimensions:
      width: "100%"
      height: 40
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left:
        - "osk_button"
        - "komorebi_workspaces"
        - "active_window"
      center:
        - "clock"
      right:
        - "cpu"
        - "memory"
        - "battery"
        - "volume"

widgets:
  osk_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "<span class='icon'>\uf11c</span>"
      label_alt: "<span class='icon'>\uf11c</span>"
      class_name: "osk-btn"
      exec_options:
        run_cmd: "echo osk"
        run_once: true
      callbacks:
        on_left: "exec cmd.exe /c start osk.exe"

  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "Komorebi Offline"
      label_workspace_btn: "{index}"
      label_workspace_active_btn: "{index}"
      label_workspace_populated_btn: "{index}"
      label_default_name: "{index}"
      label_zero_index: false
      hide_empty_workspaces: true
      hide_if_offline: true
      animation: true

  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[{win[process][name]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 50
      max_length_ellipsis: "..."
      monitor_exclusive: true
      callbacks:
        on_left: "toggle_label"

  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span class='icon'>\uf017</span> {%d/%m %H:%M}"
      label_alt: "<span class='icon'>\uf017</span> {%A %d %B %Y %H:%M:%S}"
      callbacks:
        on_left: "toggle_label"

  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span class='icon'>\uf4bc</span>{info[percent][total]}%"
      label_alt: "<span class='icon'>\uf4bc</span> {info[percent][total]}%"
      update_interval: 2000
      callbacks:
        on_left: "toggle_label"

  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span class='icon'>\uefc5</span> {virtual_mem_percent}%"
      label_alt: "<span class='icon'>\uefc5</span> {virtual_mem_free}"
      update_interval: 2000
      callbacks:
        on_left: "toggle_label"

  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "{icon}  {percent}%"
      label_alt: "{icon}  {percent}% {time_remaining}"
      update_interval: 10000

  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span class='icon'>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8"
        - "\uf026"
        - "\uf027"
        - "\uf027"
        - "\uf028"
      callbacks:
        on_left: "toggle_mute"
        on_right: "exec cmd.exe /c start ms-settings:sound"
